<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Lively.Common.Linux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tmds.DBus" Version="0.21.2" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.8.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lively.Common\Lively.Common.csproj" />
    <ProjectReference Include="..\Lively.Models\Lively.Models.csproj" />
  </ItemGroup>

</Project>
