<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net9.0;net472</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NPSMLib" Version="0.9.14" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lively.Common\Lively.Common.csproj" />
    <ProjectReference Include="..\Lively.Common.Windows\Lively.Common.Windows.csproj" />
    <ProjectReference Include="..\Lively.Models\Lively.Models.csproj" />
  </ItemGroup>

</Project>
